// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

#pragma once

#include "calculator.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCalculator final : ::djinni::JniInterface<::calculator::Calculator, NativeCalculator> {
public:
    using CppType = std::shared_ptr<::calculator::Calculator>;
    using CppOptType = std::shared_ptr<::calculator::Calculator>;
    using JniType = jobject;

    using Boxed = NativeCalculator;

    ~NativeCalculator();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCalculator>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCalculator>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCalculator();
    friend ::djinni::JniClass<NativeCalculator>;
    friend ::djinni::JniInterface<::calculator::Calculator, NativeCalculator>;

};

}  // namespace djinni_generated
