// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from calculator.djinni

#include "calculator.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWCalculator;

namespace djinni_generated {

class Calculator
{
public:
    using CppType = std::shared_ptr<::calculator::Calculator>;
    using CppOptType = std::shared_ptr<::calculator::Calculator>;
    using ObjcType = HWCalculator*;

    using Boxed = Calculator;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

