// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fibonacci.djinni

package com.example.juntung1;

public abstract class MyClientInterface {
    public abstract boolean logString(String str);
}
