// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from calculator.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace calculator {

class Calculator {
public:
    virtual ~Calculator() {}

    static std::shared_ptr<Calculator> create();

    virtual int32_t summation(int32_t number1, int32_t number2) = 0;

    virtual int32_t multiplication(int32_t number1, int32_t number2) = 0;

    virtual int32_t subtraction(int32_t number1, int32_t number2) = 0;

    virtual int32_t division(int32_t number1, int32_t number2) = 0;
};

}  // namespace calculator
